//! Versioned search transport types and provider-neutral session lifecycle.
//!
//! Storage and provider workers use the typed query parser separately. This
//! module owns only request identity, result metadata, opaque cursors, and the
//! cancellation signal that prevents stale work from being published.

use crate::{AccountId, MailConversation, MailCursor};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeMap, HashMap, HashSet},
    sync::{
        atomic::{AtomicBool, Ordering},
        Arc, Mutex,
    },
};
use tokio::sync::Notify;
use uuid::Uuid;

pub const SEARCH_REQUEST_V2_VERSION: u8 = 2;
pub const DEFAULT_SEARCH_PAGE_SIZE: u32 = 50;
pub const MAX_SEARCH_PAGE_SIZE: u32 = 500;
/// A client can cancel before its initial IPC call has registered a session.
/// Keep only a small bounded tombstone set so malformed clients cannot retain
/// unbounded UUIDs indefinitely.
const MAX_PENDING_CLIENT_CANCELLATIONS: usize = 1_024;

/// The raw, versioned request passed across the desktop boundary. The query is
/// intentionally raw: parsing remains a Rust-only operation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchRequestV2 {
    pub raw_query: String,
    /// An optional UUID generated by the client before `start_search` begins.
    /// It closes the cancellation race where no server session ID exists yet.
    #[serde(default)]
    pub client_request_id: Option<Uuid>,
    #[serde(default)]
    pub account_ids: Vec<AccountId>,
    #[serde(default)]
    pub scope: SearchScopeV2,
    #[serde(default)]
    pub execution_mode: SearchExecutionMode,
    #[serde(default = "default_search_page_size")]
    pub page_size: u32,
    #[serde(default)]
    pub continuation: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchScopeV2 {
    #[serde(default)]
    pub mailbox: Option<String>,
    #[serde(default)]
    pub include_spam_trash: bool,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SearchExecutionMode {
    /// Never send the query to an account provider.
    Local,
    /// Use local results immediately and a separately scheduled provider pass.
    #[default]
    Hybrid,
}

/// Account or mailbox coverage emitted even when another source fails.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchCoverage {
    pub account_id: AccountId,
    #[serde(default)]
    pub mailbox: Option<String>,
    pub state: SearchCoverageState,
    #[serde(default)]
    pub detail: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SearchCoverageState {
    LocalCatalogue,
    LocalBodyIndex,
    ProviderSearched,
    ProviderPartial,
    Offline,
    AuthenticationFailed,
    Unsupported,
    Cancelled,
    MailboxChanged,
}

/// Why a conversation is present in a search page. The IDs are local opaque
/// IDs, not IMAP UIDs, so a caller cannot reuse a stale provider UID.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct SearchMatchEvidence {
    #[serde(default)]
    pub primary_message_id: Option<String>,
    #[serde(default)]
    pub matched_message_ids: Vec<String>,
    pub match_count: u32,
    #[serde(default)]
    pub excerpt: Option<String>,
}

/// The concrete desktop result shape. Provider-specific workers supply the
/// conversations, but coverage and evidence retain one stable contract.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchPageV2 {
    pub conversations: Vec<MailConversation>,
    #[serde(default)]
    pub match_evidence: BTreeMap<String, SearchMatchEvidence>,
    #[serde(default)]
    pub coverage: Vec<SearchCoverage>,
    #[serde(default)]
    pub continuation: Option<String>,
    pub session_id: Uuid,
    pub revision: u64,
}

/// A safe, displayable error returned for parsing, unsupported syntax, or a
/// source failure. It never requires the caller to inspect provider errors.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchErrorV2 {
    #[serde(default)]
    pub position: Option<usize>,
    pub category: SearchErrorCategory,
    #[serde(default)]
    pub unsupported_operator: Option<String>,
    pub message: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SearchErrorCategory {
    Parse,
    Unsupported,
    Provider,
    Transient,
}

impl From<crate::search::SearchParseError> for SearchErrorV2 {
    fn from(error: crate::search::SearchParseError) -> Self {
        use crate::search::SearchParseErrorKind;

        match error.kind {
            SearchParseErrorKind::UnsupportedOperator { operator } => Self {
                position: Some(error.position),
                category: SearchErrorCategory::Unsupported,
                unsupported_operator: Some(operator),
                message: "This search operator is not supported yet.".into(),
            },
            _ => Self {
                position: Some(error.position),
                category: SearchErrorCategory::Parse,
                unsupported_operator: None,
                message: "The search query is invalid.".into(),
            },
        }
    }
}

impl SearchRequestV2 {
    /// Clamp a page size at the boundary so providers cannot be asked for an
    /// unbounded page when a caller supplies malformed IPC input.
    pub fn effective_page_size(&self) -> u32 {
        match self.page_size {
            0 => DEFAULT_SEARCH_PAGE_SIZE,
            size => size.min(MAX_SEARCH_PAGE_SIZE),
        }
    }

    /// A stable identity for a query and its scope. Pagination itself is not
    /// included, so each later page validates against the same search.
    pub fn query_hash(&self) -> String {
        let fingerprint = SearchRequestFingerprint {
            version: SEARCH_REQUEST_V2_VERSION,
            raw_query: &self.raw_query,
            account_ids: &self.account_ids,
            scope: &self.scope,
            execution_mode: self.execution_mode,
        };
        let encoded = serde_json::to_vec(&fingerprint)
            .expect("SearchRequestFingerprint only contains serializable primitive fields");
        let digest = Sha256::digest(encoded);
        hex_digest(&digest)
    }

    /// Decode and bind an opaque continuation to this exact request.
    pub fn decode_continuation(
        &self,
    ) -> Result<Option<SearchContinuationV2>, SearchContinuationError> {
        self.continuation
            .as_deref()
            .map(SearchContinuationV2::decode)
            .transpose()?
            .map(|continuation| {
                continuation.validate_for(self)?;
                Ok(continuation)
            })
            .transpose()
    }
}

fn default_search_page_size() -> u32 {
    DEFAULT_SEARCH_PAGE_SIZE
}

#[derive(Serialize)]
struct SearchRequestFingerprint<'a> {
    version: u8,
    raw_query: &'a str,
    account_ids: &'a [AccountId],
    scope: &'a SearchScopeV2,
    execution_mode: SearchExecutionMode,
}

/// An encoded, implementation-private cursor. Its fields are public solely so
/// providers can resume their own opaque offset after validation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchContinuationV2 {
    version: u8,
    pub session_id: Uuid,
    pub query_hash: String,
    pub offset: u64,
    #[serde(default)]
    pub local_cursor: Option<MailCursor>,
    /// Candidate progress is distinct from the public result cursor. It is
    /// only accepted after the continuation has been bound to its active
    /// session and query fingerprint.
    #[serde(default)]
    pub local_candidate_cursor: Option<MailCursor>,
}

impl SearchContinuationV2 {
    pub fn new(session: &SearchSession, request: &SearchRequestV2, offset: u64) -> Self {
        Self {
            version: SEARCH_REQUEST_V2_VERSION,
            session_id: session.session_id,
            query_hash: request.query_hash(),
            offset,
            local_cursor: None,
            local_candidate_cursor: None,
        }
    }

    pub fn with_local_cursor(mut self, local_cursor: Option<MailCursor>) -> Self {
        self.local_cursor = local_cursor;
        self
    }

    pub fn with_local_candidate_cursor(mut self, cursor: Option<MailCursor>) -> Self {
        self.local_candidate_cursor = cursor;
        self
    }

    pub fn encode(&self) -> String {
        let serialized = serde_json::to_vec(self)
            .expect("SearchContinuationV2 only contains serializable primitive fields");
        URL_SAFE_NO_PAD.encode(serialized)
    }

    pub fn decode(encoded: &str) -> Result<Self, SearchContinuationError> {
        let bytes = URL_SAFE_NO_PAD
            .decode(encoded)
            .map_err(|_| SearchContinuationError::Invalid)?;
        let continuation =
            serde_json::from_slice::<Self>(&bytes).map_err(|_| SearchContinuationError::Invalid)?;
        if continuation.version != SEARCH_REQUEST_V2_VERSION {
            return Err(SearchContinuationError::UnsupportedVersion);
        }
        Ok(continuation)
    }

    pub fn validate_for(&self, request: &SearchRequestV2) -> Result<(), SearchContinuationError> {
        if self.query_hash != request.query_hash() {
            return Err(SearchContinuationError::QueryMismatch);
        }
        Ok(())
    }
}

/// Per-mailbox provider progress kept only for the lifetime of an active
/// submitted search. This is deliberately not sent to TypeScript: the public
/// continuation carries only a session-bound local cursor.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProviderSearchCursor {
    /// Descending IMAP UID cursor for each mailbox. Newly arrived higher UIDs
    /// cannot shift this anchor, unlike an offset into a fresh SEARCH result.
    pub mailbox_last_uid: BTreeMap<String, u32>,
    /// The UID namespace which owns each UID anchor. IMAP is allowed to reuse
    /// UID numbers after a UIDVALIDITY rollover, so an anchor alone is never a
    /// valid continuation identity. This stays session-private just like the
    /// UID anchor and is checked again for every SELECT and candidate FETCH.
    pub mailbox_uid_validity: BTreeMap<String, u32>,
    /// Starting mailbox for the next small provider page. This remains
    /// session-private alongside UID anchors, so continuations can share a
    /// fair round without exposing provider paths to the UI.
    pub mailbox_round_offset: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SearchContinuationError {
    Invalid,
    UnsupportedVersion,
    QueryMismatch,
}

/// A clonable cancellation token passed to local and provider workers.
#[derive(Debug, Clone)]
pub struct SearchSession {
    pub session_id: Uuid,
    pub revision: u64,
    pub query_hash: String,
    /// Requested account scope, retained only while this native session is
    /// live. An empty list means the caller selected every enabled account.
    account_ids: Vec<AccountId>,
    cancelled: Arc<AtomicBool>,
    cancelled_notify: Arc<Notify>,
}

impl SearchSession {
    pub fn is_cancelled(&self) -> bool {
        self.cancelled.load(Ordering::Acquire)
    }

    /// Wait for cancellation without polling a provider timeout.  Register
    /// the notification before checking the atomic flag so a cancellation in
    /// between cannot be missed.
    pub async fn cancelled(&self) {
        loop {
            let notified = self.cancelled_notify.notified();
            if self.is_cancelled() {
                return;
            }
            notified.await;
        }
    }

    fn cancel(&self) {
        if !self.cancelled.swap(true, Ordering::AcqRel) {
            self.cancelled_notify.notify_waiters();
        }
    }
}

/// Tracks active submitted searches. Starting a new session supersedes all
/// earlier sessions in this registry, which prevents stale provider events
/// from winning a race with the user's newer explicit submission.
#[derive(Debug, Default)]
pub struct SearchSessionRegistry {
    state: Mutex<SearchSessionRegistryState>,
}

#[derive(Debug, Default)]
struct SearchSessionRegistryState {
    next_revision: u64,
    active: HashMap<Uuid, SearchSession>,
    provider_progress: HashMap<(Uuid, AccountId), ProviderSearchProgress>,
    provider_message_ids: HashMap<Uuid, Vec<String>>,
    provider_round_offsets: HashMap<Uuid, usize>,
    emitted_conversation_ids: HashMap<Uuid, std::collections::HashSet<String>>,
    cancelled_before_begin: HashSet<Uuid>,
    begun_session_ids: HashSet<Uuid>,
    finished_session_ids: HashSet<Uuid>,
}

#[derive(Debug, Clone, Default)]
struct ProviderSearchProgress {
    cursor: ProviderSearchCursor,
    exhausted: bool,
}

impl SearchSessionRegistry {
    pub fn begin(&self, request: &SearchRequestV2) -> SearchSession {
        let mut state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let session_id = request.client_request_id.unwrap_or_else(Uuid::new_v4);
        // Consume a pre-start cancellation before touching the current
        // session. IPC can deliver an old, already-cancelled start after the
        // user has submitted a newer query; that late request must not
        // supersede the newer active work merely so its cancellation is
        // observed.
        if state.cancelled_before_begin.remove(&session_id) {
            let session = SearchSession {
                session_id,
                revision: state.next_revision,
                query_hash: request.query_hash(),
                account_ids: request.account_ids.clone(),
                cancelled: Arc::new(AtomicBool::new(true)),
                cancelled_notify: Arc::new(Notify::new()),
            };
            // Keep the cancelled session addressable only long enough for the
            // start command's idempotent `cancel` cleanup. It deliberately
            // coexists with the current active session rather than replacing
            // it.
            state.active.insert(session.session_id, session.clone());
            state.begun_session_ids.insert(session.session_id);
            return session;
        }
        let superseded = state.active.values().cloned().collect::<Vec<_>>();
        for session in &superseded {
            session.cancel();
        }
        // Starting a new submitted search supersedes every older one. Their
        // cursors, queued IDs, and emitted-conversation state are unusable and
        // must not outlive the session. Keep only a bounded finished-ID record
        // for cancellation idempotence.
        for session in superseded {
            state.begun_session_ids.remove(&session.session_id);
            remember_finished_session(&mut state, session.session_id);
        }
        state.active.clear();
        state.provider_progress.clear();
        state.provider_message_ids.clear();
        state.provider_round_offsets.clear();
        state.emitted_conversation_ids.clear();
        state.next_revision = state.next_revision.saturating_add(1);
        // A client may intentionally retry with an ID only after its previous
        // request finished. That is a new session, not a second cancellation.
        state.finished_session_ids.remove(&session_id);
        let session = SearchSession {
            session_id,
            revision: state.next_revision,
            query_hash: request.query_hash(),
            account_ids: request.account_ids.clone(),
            cancelled: Arc::new(AtomicBool::new(false)),
            cancelled_notify: Arc::new(Notify::new()),
        };
        state.active.insert(session.session_id, session.clone());
        state.begun_session_ids.insert(session.session_id);
        session
    }

    /// Mark a session cancelled. Returns false for an unknown or already
    /// completed session, allowing Tauri cancellation to stay idempotent.
    pub fn cancel(&self, session_id: Uuid) -> bool {
        let mut state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let Some(session) = state.active.remove(&session_id) else {
            if state.finished_session_ids.contains(&session_id) {
                return false;
            }
            if state.begun_session_ids.contains(&session_id) {
                return false;
            }
            if state.cancelled_before_begin.len() >= MAX_PENDING_CLIENT_CANCELLATIONS {
                // These IDs have never begun. Evict one old-unmatched entry to
                // bound cancellation-race memory; clients may safely retry a
                // cancellation if their initial request has not arrived yet.
                if let Some(expired) = state.cancelled_before_begin.iter().next().copied() {
                    state.cancelled_before_begin.remove(&expired);
                }
            }
            return state.cancelled_before_begin.insert(session_id);
        };
        state
            .provider_progress
            .retain(|(active_session_id, _), _| *active_session_id != session_id);
        state.provider_message_ids.remove(&session_id);
        state.provider_round_offsets.remove(&session_id);
        state.emitted_conversation_ids.remove(&session_id);
        state.begun_session_ids.remove(&session_id);
        remember_finished_session(&mut state, session_id);
        session.cancel();
        true
    }

    /// Invalidate submitted searches affected by a mutable account operation.
    /// An unscoped request searches every enabled account, so it is affected by
    /// any account change. The actual cleanup is delegated to `cancel` after
    /// releasing the registry lock to keep cancellation paths non-reentrant.
    pub fn cancel_account(&self, account_id: AccountId) -> usize {
        let session_ids = {
            let state = self
                .state
                .lock()
                .expect("search session registry lock poisoned");
            state
                .active
                .values()
                .filter(|session| {
                    session.account_ids.is_empty() || session.account_ids.contains(&account_id)
                })
                .map(|session| session.session_id)
                .collect::<Vec<_>>()
        };
        session_ids
            .into_iter()
            .filter(|session_id| self.cancel(*session_id))
            .count()
    }

    /// Mark an exact session as complete. A stale worker cannot accidentally
    /// remove the newer active session because ID and revision must agree.
    pub fn complete(&self, session: &SearchSession) -> bool {
        let mut state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let Some(active) = state.active.get(&session.session_id) else {
            return false;
        };
        if active.revision != session.revision {
            return false;
        }
        state.active.remove(&session.session_id);
        state
            .provider_progress
            .retain(|(active_session_id, _), _| *active_session_id != session.session_id);
        state.provider_message_ids.remove(&session.session_id);
        state.provider_round_offsets.remove(&session.session_id);
        state.emitted_conversation_ids.remove(&session.session_id);
        state.begun_session_ids.remove(&session.session_id);
        remember_finished_session(&mut state, session.session_id);
        true
    }

    /// Gets the exact per-account provider cursor for this active session.
    /// A missing entry is a fresh provider page, never an exhausted one.
    pub fn provider_progress(
        &self,
        session: &SearchSession,
        account_id: AccountId,
    ) -> Option<(ProviderSearchCursor, bool)> {
        let state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let active = state.active.get(&session.session_id)?;
        if active.revision != session.revision || active.is_cancelled() {
            return None;
        }
        let progress = state
            .provider_progress
            .get(&(session.session_id, account_id))
            .cloned()
            .unwrap_or_default();
        Some((progress.cursor, progress.exhausted))
    }

    pub fn set_provider_progress(
        &self,
        session: &SearchSession,
        account_id: AccountId,
        cursor: ProviderSearchCursor,
        exhausted: bool,
    ) -> bool {
        let mut state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let Some(active) = state.active.get(&session.session_id) else {
            return false;
        };
        if active.revision != session.revision || active.is_cancelled() {
            return false;
        }
        state.provider_progress.insert(
            (session.session_id, account_id),
            ProviderSearchProgress { cursor, exhausted },
        );
        true
    }

    /// Returns the rotating first account for the next provider round. The
    /// caller supplies only non-exhausted accounts, and uses the resulting
    /// offset to distribute a bounded candidate budget fairly. Rotating here,
    /// rather than in the public continuation, keeps provider scheduling
    /// session-private and resistant to reordered client requests.
    pub fn next_provider_round_offset(
        &self,
        session: &SearchSession,
        active_account_count: usize,
        page_size: usize,
    ) -> Option<usize> {
        if active_account_count == 0 {
            return None;
        }
        let mut state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let active = state.active.get(&session.session_id)?;
        if active.revision != session.revision || active.is_cancelled() {
            return None;
        }
        let offset = state
            .provider_round_offsets
            .entry(session.session_id)
            .or_default();
        let start = *offset % active_account_count;
        *offset = start.saturating_add(page_size.max(1)) % active_account_count;
        Some(start)
    }

    /// Queues provider matches until the public page has capacity. IDs are
    /// session-owned so a later UID batch cannot be lost merely because its
    /// message date sorts before the local continuation cursor.
    pub fn enqueue_provider_message_ids(
        &self,
        session: &SearchSession,
        message_ids: impl IntoIterator<Item = String>,
    ) -> bool {
        let mut state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let Some(active) = state.active.get(&session.session_id) else {
            return false;
        };
        if active.revision != session.revision || active.is_cancelled() {
            return false;
        }
        let queued = state
            .provider_message_ids
            .entry(session.session_id)
            .or_default();
        for id in message_ids {
            if !queued.contains(&id) {
                queued.push(id);
            }
        }
        true
    }

    /// Queue at most `capacity` unique provider IDs for one public page. This
    /// is a second safety boundary behind Tauri's fair round budget, so a
    /// concurrent or malformed caller cannot retain unbounded candidates.
    pub fn enqueue_provider_message_ids_bounded(
        &self,
        session: &SearchSession,
        message_ids: impl IntoIterator<Item = String>,
        capacity: usize,
    ) -> bool {
        let mut state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let Some(active) = state.active.get(&session.session_id) else {
            return false;
        };
        if active.revision != session.revision || active.is_cancelled() {
            return false;
        }
        let queued = state
            .provider_message_ids
            .entry(session.session_id)
            .or_default();
        for id in message_ids {
            if queued.len() >= capacity {
                break;
            }
            if !queued.contains(&id) {
                queued.push(id);
            }
        }
        true
    }

    pub fn take_provider_message_ids(&self, session: &SearchSession, limit: usize) -> Vec<String> {
        let mut state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let Some(active) = state.active.get(&session.session_id) else {
            return Vec::new();
        };
        if active.revision != session.revision || active.is_cancelled() {
            return Vec::new();
        }
        let queued = state
            .provider_message_ids
            .entry(session.session_id)
            .or_default();
        let count = limit.min(queued.len());
        queued.drain(..count).collect()
    }

    pub fn has_pending_provider_messages(&self, session: &SearchSession) -> bool {
        let state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        state
            .provider_message_ids
            .get(&session.session_id)
            .is_some_and(|ids| !ids.is_empty())
    }

    /// A V2 local page passes these IDs back into storage so a thread whose
    /// older matching message appears after the candidate keyset never
    /// reappears on a later page. The set is scoped to the active session and
    /// removed on completion or cancellation.
    pub fn emitted_conversation_ids(&self, session: &SearchSession) -> Vec<String> {
        let state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let Some(active) = state.active.get(&session.session_id) else {
            return Vec::new();
        };
        if active.revision != session.revision || active.is_cancelled() {
            return Vec::new();
        }
        state
            .emitted_conversation_ids
            .get(&session.session_id)
            .map(|ids| ids.iter().cloned().collect())
            .unwrap_or_default()
    }

    /// Returns true exactly once for each conversation in an active session.
    pub fn mark_conversation_emitted(
        &self,
        session: &SearchSession,
        conversation_id: &str,
    ) -> bool {
        let mut state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let Some(active) = state.active.get(&session.session_id) else {
            return false;
        };
        if active.revision != session.revision || active.is_cancelled() {
            return false;
        }
        state
            .emitted_conversation_ids
            .entry(session.session_id)
            .or_default()
            .insert(conversation_id.to_owned())
    }

    pub fn is_current(&self, session: &SearchSession) -> bool {
        if session.is_cancelled() {
            return false;
        }
        let state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        state
            .active
            .get(&session.session_id)
            .is_some_and(|active| active.revision == session.revision && !active.is_cancelled())
    }

    /// Returns a current session only when its continuation still belongs to
    /// the exact submitted query.  The returned clone shares the cancellation
    /// flag with the registry entry.
    pub fn current_for(
        &self,
        session_id: Uuid,
        request: &SearchRequestV2,
    ) -> Option<SearchSession> {
        let state = self
            .state
            .lock()
            .expect("search session registry lock poisoned");
        let session = state.active.get(&session_id)?;
        (session.query_hash == request.query_hash() && !session.is_cancelled())
            .then(|| session.clone())
    }
}

fn remember_finished_session(state: &mut SearchSessionRegistryState, session_id: Uuid) {
    if state.finished_session_ids.len() >= MAX_PENDING_CLIENT_CANCELLATIONS {
        if let Some(expired) = state.finished_session_ids.iter().next().copied() {
            state.finished_session_ids.remove(&expired);
        }
    }
    state.finished_session_ids.insert(session_id);
}

fn hex_digest(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        output.push(char::from(HEX[usize::from(byte >> 4)]));
        output.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::search::{parse_search_query, SearchParseErrorKind};

    fn request(raw_query: &str) -> SearchRequestV2 {
        SearchRequestV2 {
            raw_query: raw_query.into(),
            client_request_id: None,
            account_ids: vec![Uuid::from_u128(1)],
            scope: SearchScopeV2 {
                mailbox: Some("Inbox".into()),
                include_spam_trash: false,
            },
            execution_mode: SearchExecutionMode::Hybrid,
            page_size: 100,
            continuation: None,
        }
    }

    #[test]
    fn query_hash_binds_the_raw_query_scope_accounts_and_execution_mode() {
        let original = request("from:alice");
        let mut changed = original.clone();
        changed.raw_query = "from:bob".into();
        assert_ne!(original.query_hash(), changed.query_hash());
        changed = original.clone();
        changed.scope.mailbox = Some("Archive".into());
        assert_ne!(original.query_hash(), changed.query_hash());
        changed = original.clone();
        changed.execution_mode = SearchExecutionMode::Local;
        assert_ne!(original.query_hash(), changed.query_hash());
    }

    #[test]
    fn continuation_is_opaque_and_rejects_a_different_query() {
        let registry = SearchSessionRegistry::default();
        let original = request("subject:invoice");
        let session = registry.begin(&original);
        let encoded = SearchContinuationV2::new(&session, &original, 50).encode();
        assert!(!encoded.contains("subject:invoice"));
        let mut resumed = original.clone();
        resumed.continuation = Some(encoded);
        assert_eq!(resumed.decode_continuation().unwrap().unwrap().offset, 50);
        resumed.raw_query = "subject:receipt".into();
        assert_eq!(
            resumed.decode_continuation(),
            Err(SearchContinuationError::QueryMismatch)
        );
        assert_eq!(
            SearchContinuationV2::decode("not-a-cursor"),
            Err(SearchContinuationError::Invalid)
        );
    }

    #[test]
    fn newer_sessions_cancel_and_supersede_older_work() {
        let registry = SearchSessionRegistry::default();
        let first = registry.begin(&request("first"));
        assert!(registry.is_current(&first));
        let second = registry.begin(&request("second"));
        assert!(first.is_cancelled());
        assert!(!registry.is_current(&first));
        assert!(registry.is_current(&second));
        assert!(second.revision > first.revision);
        assert!(!registry.complete(&first));
        assert!(registry.complete(&second));
        assert!(!registry.is_current(&second));
    }

    #[test]
    fn cancellation_tombstone_applies_when_the_initial_search_has_not_begun() {
        let registry = SearchSessionRegistry::default();
        let mut request = request("body:invoice");
        let client_request_id = Uuid::from_u128(77);
        request.client_request_id = Some(client_request_id);
        assert!(registry.cancel(client_request_id));
        let session = registry.begin(&request);
        assert_eq!(session.session_id, client_request_id);
        assert!(session.is_cancelled());
        assert!(!registry.is_current(&session));
    }

    #[test]
    fn cancelled_late_start_does_not_supersede_a_newer_active_session() {
        let registry = SearchSessionRegistry::default();
        let active = registry.begin(&request("newer query"));
        let mut late = request("older query");
        late.client_request_id = Some(Uuid::from_u128(78));
        assert!(registry.cancel(late.client_request_id.unwrap()));

        let cancelled_late = registry.begin(&late);
        assert!(cancelled_late.is_cancelled());
        assert!(registry.is_current(&active));
        assert_eq!(
            registry
                .current_for(active.session_id, &request("newer query"))
                .map(|session| session.session_id),
            Some(active.session_id)
        );
        assert!(registry.cancel(cancelled_late.session_id));
        assert!(registry.is_current(&active));
    }

    #[test]
    fn account_mutation_cancels_scoped_and_unscoped_searches() {
        let account_a = Uuid::from_u128(101);
        let account_b = Uuid::from_u128(102);
        let mut scoped_request = request("account a");
        scoped_request.account_ids = vec![account_a];
        let scoped_registry = SearchSessionRegistry::default();
        let scoped = scoped_registry.begin(&scoped_request);
        assert_eq!(scoped_registry.cancel_account(account_b), 0);
        assert!(scoped_registry.is_current(&scoped));
        assert_eq!(scoped_registry.cancel_account(account_a), 1);
        assert!(scoped.is_cancelled());

        let unscoped_registry = SearchSessionRegistry::default();
        let mut unscoped_request = request("all accounts");
        unscoped_request.account_ids.clear();
        let unscoped = unscoped_registry.begin(&unscoped_request);
        assert_eq!(unscoped_registry.cancel_account(account_b), 1);
        assert!(unscoped.is_cancelled());
    }

    #[test]
    fn pre_start_cancellation_tombstones_are_consumed_and_bounded() {
        let registry = SearchSessionRegistry::default();
        let mut request = request("body:invoice");
        let client_request_id = Uuid::from_u128(91);
        request.client_request_id = Some(client_request_id);
        assert!(registry.cancel(client_request_id));
        let cancelled = registry.begin(&request);
        assert!(cancelled.is_cancelled());
        {
            let state = registry.state.lock().unwrap();
            assert!(!state.cancelled_before_begin.contains(&client_request_id));
        }
        assert!(registry.cancel(cancelled.session_id));

        for id in 0..(MAX_PENDING_CLIENT_CANCELLATIONS + 128) {
            assert!(registry.cancel(Uuid::from_u128(10_000 + id as u128)));
        }
        let state = registry.state.lock().unwrap();
        assert!(state.cancelled_before_begin.len() <= MAX_PENDING_CLIENT_CANCELLATIONS);
        assert!(state.begun_session_ids.is_empty());
        assert!(state.finished_session_ids.len() <= MAX_PENDING_CLIENT_CANCELLATIONS);
    }

    #[test]
    fn repeated_begin_supersedes_and_bounds_all_session_owned_state() {
        let registry = SearchSessionRegistry::default();
        let account_id = Uuid::from_u128(55);
        for index in 0..(MAX_PENDING_CLIENT_CANCELLATIONS + 128) {
            let mut request = request("invoice");
            request.client_request_id = Some(Uuid::from_u128(20_000 + index as u128));
            let session = registry.begin(&request);
            assert!(registry.set_provider_progress(
                &session,
                account_id,
                ProviderSearchCursor::default(),
                false,
            ));
            assert!(registry.enqueue_provider_message_ids(&session, [format!("message-{index}")]));
            assert!(registry.mark_conversation_emitted(&session, &format!("thread-{index}")));
        }
        let state = registry.state.lock().unwrap();
        assert_eq!(state.active.len(), 1);
        assert_eq!(state.provider_progress.len(), 1);
        assert_eq!(state.provider_message_ids.len(), 1);
        assert_eq!(state.emitted_conversation_ids.len(), 1);
        assert_eq!(state.begun_session_ids.len(), 1);
        assert!(state.finished_session_ids.len() <= MAX_PENDING_CLIENT_CANCELLATIONS);
    }

    #[test]
    fn current_for_binds_pagination_to_the_active_query() {
        let registry = SearchSessionRegistry::default();
        let request = request("from:person@example.test");
        let session = registry.begin(&request);
        assert_eq!(
            registry
                .current_for(session.session_id, &request)
                .map(|current| current.session_id),
            Some(session.session_id)
        );
        let mut changed = request.clone();
        changed.raw_query = "from:other@example.test".into();
        assert!(registry.current_for(session.session_id, &changed).is_none());
        assert!(registry.cancel(session.session_id));
        assert!(registry.current_for(session.session_id, &request).is_none());
    }

    #[test]
    fn provider_progress_is_session_bound_and_survives_later_pages() {
        let registry = SearchSessionRegistry::default();
        let request = request("body:invoice");
        let session = registry.begin(&request);
        let account_id = Uuid::from_u128(88);
        let mut cursor = ProviderSearchCursor::default();
        cursor.mailbox_last_uid.insert("INBOX".into(), 50);
        assert!(registry.set_provider_progress(&session, account_id, cursor.clone(), false));
        assert_eq!(
            registry.provider_progress(&session, account_id),
            Some((cursor, false))
        );
        assert!(registry.cancel(session.session_id));
        assert!(registry.provider_progress(&session, account_id).is_none());
    }

    #[test]
    fn queued_provider_matches_survive_a_full_page_without_date_cursor_loss() {
        let registry = SearchSessionRegistry::default();
        let request = request("body:invoice");
        let session = registry.begin(&request);
        assert!(registry.enqueue_provider_message_ids(
            &session,
            ["uid-old-date-new".into(), "later-provider-hit".into()]
        ));
        assert_eq!(
            registry.take_provider_message_ids(&session, 1),
            vec!["uid-old-date-new"]
        );
        assert!(registry.has_pending_provider_messages(&session));
        assert_eq!(
            registry.take_provider_message_ids(&session, 50),
            vec!["later-provider-hit"]
        );
        assert!(!registry.has_pending_provider_messages(&session));
    }

    #[test]
    fn emitted_conversation_ids_deduplicate_provider_and_local_pages() {
        let registry = SearchSessionRegistry::default();
        let request = request("invoice");
        let session = registry.begin(&request);
        assert!(registry.mark_conversation_emitted(&session, "account:thread-1"));
        assert!(!registry.mark_conversation_emitted(&session, "account:thread-1"));
    }

    #[test]
    fn local_cursor_continuation_is_opaque_and_keeps_pagination_past_500() {
        let registry = SearchSessionRegistry::default();
        let request = request("invoice");
        let session = registry.begin(&request);
        let cursor = SearchContinuationV2::new(&session, &request, 500)
            .with_local_cursor(Some(MailCursor {
                received_at: chrono::Utc::now(),
                id: "message-500".into(),
            }))
            .with_local_candidate_cursor(Some(MailCursor {
                received_at: chrono::Utc::now(),
                id: "candidate-500".into(),
            }));
        let mut resumed = request.clone();
        resumed.continuation = Some(cursor.encode());
        let decoded = resumed.decode_continuation().unwrap().unwrap();
        assert_eq!(decoded.offset, 500);
        assert_eq!(decoded.local_cursor.unwrap().id, "message-500");
        assert_eq!(decoded.local_candidate_cursor.unwrap().id, "candidate-500");
    }

    #[test]
    fn cancellation_is_idempotent_and_page_size_is_bounded() {
        let registry = SearchSessionRegistry::default();
        let session = registry.begin(&request("invoice"));
        assert!(registry.cancel(session.session_id));
        assert!(session.is_cancelled());
        assert!(!registry.cancel(session.session_id));
        let mut page = request("invoice");
        page.page_size = 0;
        assert_eq!(page.effective_page_size(), DEFAULT_SEARCH_PAGE_SIZE);
        page.page_size = MAX_SEARCH_PAGE_SIZE + 1;
        assert_eq!(page.effective_page_size(), MAX_SEARCH_PAGE_SIZE);
    }

    #[test]
    fn parser_errors_become_safe_structured_errors() {
        let parse_error = parse_search_query("memo:value").unwrap_err();
        assert!(matches!(
            parse_error.kind,
            SearchParseErrorKind::UnsupportedOperator { .. }
        ));
        let error = SearchErrorV2::from(parse_error);
        assert_eq!(error.category, SearchErrorCategory::Unsupported);
        assert_eq!(error.unsupported_operator.as_deref(), Some("memo"));
        assert_eq!(error.message, "This search operator is not supported yet.");
    }
}
